enyo.depends(
	"$lib/layout",
	"$lib/onyx",
	"media.css",
	"swfobject.js",
	"prg.js",
	"player-timeranges.js",
	"player-htmlaudio.js",
	"player-flashaudio.js",
	"player.js",
	"playlist.js",
	"media.js"
);
